#!/bin/sh
# install ruby 1.8.7p352 build for arm-linux -- 1/29/13 brent@mbari.org
# also install modules needed for ESP unless
#   coreOnly environment variable is set
#
make -j4 all || exit 3
ESP_SUDO=${ESP_SUDO-sudo}
$ESP_SUDO make install DESTDIR=$DESTDIR || exit 1
$ESP_SUDO chown $USER .installed.list || exit 2
[ -n "$coreOnly" ] || {
  echo "   Installing extensions required by MBARI ESP:"
  PATH=.:$PATH
  $ESP_SUDO rm -f termios/*.log termios/*.so
  buildUtils clean all &&
  echo "Installing MBARI extensions..."  &&
  $ESP_SUDO ruby inst-mbari.rb $DESTDIR &&
  $ESP_SUDO ./buildUtils install &&
  $ESP_SUDO chown $USER termios/*.log termios/*.so
}
